declare module 'justgage'
declare module 'listree'
declare module 'tobii'
declare module 'vue3-clipboard'
declare module 'sweetalert2/dist/sweetalert2.js'
declare module 'mobius1-selectr'
declare module 'huebee'
